---
dependency:
  name: galaxy

driver:
  name: delegated  # Запускаем тесты на локальном хосте

platforms:
  - name: instance
    groups:
      - test
    ansible_connection: local  # Подключение как к локальному хосту

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml

verifier:
  name: testinfra
