---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    privileged: true
    volumes:
      - ./ansible:/etc/ansible
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
verifier:
  name: testinfra
